# Generated by Django 4.2.16 on 2024-11-08 13:04

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
